# Generated by Django 6.0.5 on 2026-05-25 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=10)),
                ('activity_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('factor_value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null means global/default factor usable by all orgs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='esg.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('uploader', 'Uploader'), ('analyst', 'Analyst'), ('admin', 'Admin')], default='uploader', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='esg.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RawIngestRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField()),
                ('parse_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=10)),
                ('parse_error', models.TextField(blank=True)),
                ('external_record_id', models.CharField(blank=True, max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='esg.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('quantity_unit', models.CharField(max_length=30)),
                ('normalized_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=30)),
                ('emissions_tco2e', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('suspicious', 'Suspicious'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('suspicion_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='esg.emissionfactor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='esg.organization')),
                ('source_row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_record', to='esg.rawingestrow')),
            ],
        ),
        migrations.CreateModel(
            name='RecordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('status_changed', 'Status Changed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], max_length=30)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_change_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_change_logs', to='esg.organization')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='esg.normalizedemissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('corp_travel', 'Corporate Travel')], max_length=40)),
                ('display_name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_systems', to='esg.organization')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='esg.sourcesystem'),
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/esg/%Y/%m/%d/')),
                ('file_checksum_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='esg.organization')),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='esg.sourcesystem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rawingestrow',
            name='upload_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='esg.uploadbatch'),
        ),
        migrations.AddField(
            model_name='normalizedemissionrecord',
            name='upload_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='esg.uploadbatch'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['organization', 'activity_type', 'unit'], name='esg_emissio_organiz_b3baa4_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['scope', 'valid_from'], name='esg_emissio_scope_13a1a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='uniq_user_in_org'),
        ),
        migrations.AddIndex(
            model_name='recordchangelog',
            index=models.Index(fields=['organization', 'created_at'], name='esg_recordc_organiz_d5711a_idx'),
        ),
        migrations.AddIndex(
            model_name='recordchangelog',
            index=models.Index(fields=['record', 'created_at'], name='esg_recordc_record__f763e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recordchangelog',
            index=models.Index(fields=['event_type', 'created_at'], name='esg_recordc_event_t_e4db0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcesystem',
            constraint=models.UniqueConstraint(fields=('organization', 'source_type', 'display_name'), name='uniq_source_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['organization', 'uploaded_at'], name='esg_uploadb_organiz_a89228_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['source_system', 'uploaded_at'], name='esg_uploadb_source__3c24e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestrow',
            index=models.Index(fields=['organization', 'upload_batch'], name='esg_rawinge_organiz_27e48d_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawingestrow',
            constraint=models.UniqueConstraint(fields=('upload_batch', 'source_row_number'), name='uniq_row_number_per_batch'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['organization', 'status', 'scope'], name='esg_normali_organiz_6827ef_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['upload_batch', 'status'], name='esg_normali_upload__10581a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrecord',
            index=models.Index(fields=['activity_date'], name='esg_normali_activit_e8001e_idx'),
        ),
    ]
